### ISSUE TITLE
1.19 update please:)

### ISSUE THREAD

**Issue by ghost** [DeflatedPickle/PluckableArrows#10]

**Comment by mrniddala** [comment]
Hello, I was thinking it doesn't work on 1.19, because there is no 1.19.x file on Modrinth.
Thank you for confirming that it works on 1.19.x aswell:)
I have one question before this can get closed - if a player doesn't have this mod installed it is fine? Using GeyserMC.

**Comment by ghost** [comment]
Welp 🙃

![image](https://user-images.githubusercontent.com/75373609/192147002-302b3c3f-fe37-400b-a8f4-8243a877203c.png)
