### ISSUE TITLE
Arrows don't decay from player

### ISSUE THREAD

**Issue by ghost** [DeflatedPickle/PluckableArrows#3]

**Comment by DeflatedPickle** [comment]
[This isn't a bug!](https://github.com/DeflatedPickle/PluckableArrows/blob/91b9756d1edb04219eaab686c1dd56ace9748433/src/main/java/com/deflatedpickle/pluckablearrows/mixin/MixinLivingEntity.java#L84-L90)

**Comment by ghost** [comment]
I can see that it was intentional, but on singleplayer worlds it leads to just having arrows stuck in the player until they die.

**Comment by DeflatedPickle** [comment]
That's a good point! I hadn't thought about that. I'll add a way to remove them from yourself!
