### ISSUE TITLE
Unchecked cast causes crashes with models that do not implement HasPieces

### ISSUE THREAD

**Issue by itsmeow** [DeflatedPickle/PluckableArrows#4]
Pluckable Arrows 1.1.2

From https://github.com/itsmeow/betteranimalsplus/issues/293 @Chipotle4

Not sure why this crash happened considering ModelReindeer extends EntityModel and it appears you have a mixin, but there's a crash here

https://github.com/DeflatedPickle/PluckableArrows/blob/91b9756d1edb04219eaab686c1dd56ace9748433/src/main/kotlin/com/deflatedpickle/pluckablearrows/mojank/StuckObjectsFeatureRenderer.kt#L51

Here's the crash log

https://github.com/itsmeow/betteranimalsplus/files/7947473/crash-2022-01-26_22.43.52-client.txt

**Comment by DeflatedPickle** [comment]
Thanks for forwarding this my way, sorry it was reported to you! I believe that 1.1.2 didn't have the `EntityModel` mixin so the fix might be to update though it's quite an oversight on my part to not check before casting

**Comment by DeflatedPickle** [comment]
I'm guessing this is no longer being experienced so I'll close this
